apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-override
  namespace: lgtm
data:
  prometheus.yaml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      scrape_timeout: 4s

    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['localhost:8888']

      - job_name: 'kafka'
        honor_labels: true
        metrics_path: /metrics
        static_configs:
          - targets:
              - "kafka-service.default.svc.cluster.local:7071"
        metric_relabel_configs:
          - action: labeldrop
            regex: 'instance|job'
