apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: corban-gateway
  namespace: applications
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 8080

# kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/latest/download/standard-install.yaml

# helm repo add nginx-stable https://helm.nginx.com/stable
# helm repo update

# helm install nginx-gateway nginx-stable/nginx-gateway-fabric --namespace nginx-gateway --create-namespace
